services:
  eureka-server:
    build: ./apps/eureka-server
    image: eureka-server
    ports:
      - 8761:8761
    expose:
      - 8761
    networks:
      - mynetwork


  config-server:
    build: ./apps/config-server
    image: config-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    ports:
      - 8888:8888
    expose:
      - 8888
    links:
      - eureka-server
    command:
      ["./wait-for-it.sh", "eureka:8761", "--", "java", "-jar","/app.jar"]
    networks:
      - mynetwork


  user-service:
    build: ./apps/user-service
    image: user-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT="configserver:"
    depends_on:
      - eureka-server
      - config-server

  template-service:
    build: ./apps/template-service
    image: template-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server

  achievement-service:
    build: ./apps/achievement-service
    image: achievement-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge