services:
  eureka-server:
    build: ./apps/eureka-server
    image: eureka-server
    ports:
      - 8761:8761
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  config-server:
    build: ./apps/config-server
    image: config-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - GIT_USER=${GIT_USER}
      - GIT_KEY=${GIT_KEY}
    command:
      ["./wait-for-it.sh", "eureka:8761", "--", "java", "-jar","/app.jar"]
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8887/actuator/health | grep UP || exit 1"
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s


  user-service:
    build: ./apps/user-service
    image: user-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy

  template-service:
    build: ./apps/template-service
    image: template-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy

  achievement-service:
    build: ./apps/achievement-service
    image: achievement-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - 8080:8080
    depends_on:
      config-server:
        condition: service_healthy