spring.application.name=achievement-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.config.import=configserver:
logging.level.root=DEBUG

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## User Microservice Integration
#user.service.url=http://localhost:8082
#client.id=ce197337-15f3-481d-a0d7-a7dfd1022936
#client.secret=a255e986-3f58-4b78-ab24-f04ce2b24d4c
#
## RSA Public Key for JWT Validation
#rsa.public=MIIBIjANBgkqhkiG9w0BAQEFAOCAQ8AMIIBCgKCAQEAnnufy0QN3D15JFYQLAK195G3MttoAcwF6EOmEb70OUdoyU3sIa0H4v3Wmz3Z/XKarDINHd5bUaJUJ2ko3hs3pNKaMoBEokW48aDoQGsb8xcMCG4JIqQNDAwjEx+eLi6hoEuq7R42IxPnedccwfAPnmR0+v/wOTxat1CKXWV2pyQ92oh8GyjZHaOBde9SYw+Xx4jtysgNQ1a2X8HsMsOqzRomCeUHzZJ8yYHa/Rmy4roOAkBBEdUvxO3HKhcmbl+TftDCy78Zznw2gMWP0tApkrRdgCNgBJVY9DZWX0tir8LlpF77gJZkd8m9vnRqHOYjpaDVSeIWCfdajrdRPcSt5wIDAQAB
#
