spring.application.name=template-service

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server

spring.config.import=${SPRING_CONFIG_IMPORT:optional:configserver:}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true