spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: authprovider
              uri: lb://authprovider
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1